# coding=utf-8
# *** WARNING: this file was generated by pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .iam_account import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "terraform-aws-iam",
  "mod": "index",
  "fqn": "pulumi_terraform_aws_iam",
  "classes": {
   "terraform-aws-iam:index:IamAccount": "IamAccount"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "terraform-aws-iam",
  "token": "pulumi:providers:terraform-aws-iam",
  "fqn": "pulumi_terraform_aws_iam",
  "class": "Provider"
 }
]
"""
)
